#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Modified 2015 Frederick Ceder <frederick@ceders.net>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.
#
# The script takes 1 argument, which is an id for which 
# battery to monitor. Usually this is either 0 for one 
# battery. (0 or 1 for two etc.)
#
# This script is now dependent on other scripts part of 
# this git repot: https://github.com/figgefred/i3-wm-configs.git
#

use strict;
use warnings;
use utf8;

my $status;
my $percent;
my $timeleft;
my $full_text;
my $short_text;
my $batnum;
my $exec_charge = '/opt/scripts/battery-charge ';
my $exec_status = '/opt/scripts/battery-status ';
my $exec_timeleft = '/opt/scripts/battery-timeleft ';

if(@ARGV) {
   $batnum=$ARGV[0];
} else {
   $batnum=0;
}
# read the first line of the "acpi" command output

$exec_charge .= "$batnum";
$exec_status .= "$batnum";
$exec_timeleft .= "$batnum";

open (STATUS, "$exec_status |") or die "Can't exec acpi: $!\n";
$status = <STATUS>;
close(STATUS);

open (CHARGE, "$exec_charge |") or die "Can't exec acpi: $!\n";
$percent = <CHARGE>;
close(CHARGE);

open (TIME, "$exec_timeleft |") or die "Can't exec acpi: $!\n";
$timeleft = <TIME>;
close(TIME);

chomp($status);
chomp($percent);
chomp($timeleft);

$full_text = "$percent%";

if ($status eq 'Discharging') {
	$full_text .= ' DIS';
} elsif ($status eq 'Charging') {
	$full_text .= ' CHR';
} elsif ($status eq 'Full') {
   $full_text .= ' FULL';
} elsif ($status eq 'Idle') {
   $full_text .= ' IDLE';
} else {
   print "$status";
   exit(0);
}

$short_text = $full_text;
if ($timeleft) {
      $full_text .= " ($timeleft)";
} 

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

	if ($percent < 20) {
		print "#FF0000\n";
	} elsif ($percent < 40) {
		print "#FFAE00\n";
	} elsif ($percent < 60) {
		print "#FFF600\n";
	} elsif ($percent < 85) {
		print "#A8FF00\n";
	}

	if ($percent < 5) {
		exit(33);
	}
}

exit(0);
