#!/bin/bash

function print_powermode {
   local pw=$1
   if [ "${noprint}" == "false" ] ; then
      if [ "0" == ${pw} ] ; then
         echo "OFF"
         echo "OFF"
         echo "#FF0000"
      else
         echo "ACTIVE"
      fi
   fi
}

powerdown_status_file="/dev/shm/status_powerdown"

noprint=true
powerdown=`cat ${powerdown_status_file}`

if [ -z "${powerdown}" ] ; then
   # Assume powerdown is per default active
   powerdown=1
fi

if [ ! -z "$1" ] ; then
   noprint=false
   if [ -z "$2" ] ; then
      print_powermode ${powerdown}
      exit 0
   fi
fi

if [ "1" == ${powerdown} ] ; then
   sudo powerup
else
   sudo powerdown
fi

powerdown=`cat ${powerdown_status_file}`
print_powermode ${powerdown}

if [ "${powerdown}" -eq "0" ] ; then
	. /etc/default/cpupower
	if [ -z "${max_freq}" ] ; then
	        max_freq=`/opt/scripts/default-cpu-freq_max`
	fi
	sudo cpupower frequency-set --max ${max_freq} > /dev/null
	# Signal 'cpu-freq'
	pkill -RTMIN+8 i3blocks
fi

# Signal 'brightness'
pkill -RTMIN+2 i3blocks

# Signal 'cpu-governor'
pkill -RTMIN+7 i3blocks
